// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package announcement

import (
	"nez-server/api/announcement"
)

type ControllerV1 struct{}

func NewV1() announcement.IAnnouncementV1 {
	return &ControllerV1{}
}
