
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
        link: "mariadb:root:X7kP!m9qL2vR@tcp(3.87.153.255:33065)/nazhua"
        table: "nft_buy"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app