
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
        link: "mariadb:root:X7kP!m9qL2vR@tcp(3.87.153.255:33065)/nazhua"
        table: "account_token_balance,
        account_token_balance_log,
        nft_box,nft_hold,
        nft_staking,
        nft_staking_claim,
        nft_transfer,
        reward_pool_claim,
        reward_pool_join,
        reward_pool_settlement"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app