// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package staking

import (
	"nez-server/api/staking"
)

type ControllerV1 struct{}

func NewV1() staking.IStakingV1 {
	return &ControllerV1{}
}
