// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package lottery

import (
	"nez-server/api/lottery"
)

type ControllerV1 struct{}

func NewV1() lottery.ILotteryV1 {
	return &ControllerV1{}
}
