package consts

const (
	// NFT_BUY_REWARD_TYPE_USDT NFT购买奖励类型：USDT
	NFT_BUY_REWARD_TYPE_USDT = 1
	// NFT_BUY_REWARD_TYPE_POWER NFT购买奖励类型：算力
	NFT_BUY_REWARD_TYPE_POWER = 2

	// BALANCE_CHANGE_TYPE_NFT_BUY_REWARD_USDT 余额变动类型：NFT购买奖励USDT
	BALANCE_CHANGE_TYPE_NFT_BUY_REWARD_USDT = 1
	// BALANCE_CHANGE_TYPE_NFT_BUY_REWARD_USDT 余额变动类型：NFT持有奖励GP
	BALANCE_CHANGE_TYPE_NFT_HOLD_REWARD_GP = 2
	// BALANCE_CHANGE_TYPE_NFT_BUY_REWARD_USDT 余额变动类型：NFT购买奖励POWER
	BALANCE_CHANGE_TYPE_NFT_BUY_REWARD_POWER = 3
	BALANCE_CHANGE_TYPE_NFT_TOKEN_WITHDRAW   = 4

	NFT_HOLDER_REWARD_STATUS_UNFINISH = 1
	NFT_HOLDER_REWARD_STATUS_FINISH   = 2
	NFT_HOLDER_REWARD_STATUS_INVALID  = 3

	ACCOUNT_WITHDRAW_STATUS_UNFINISH = 1
	ACCOUNT_WITHDRAW_STATUS_FINISH   = 2
)
