// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalAccountTokenBalanceDao is an internal type for wrapping the internal DAO implementation.
type internalAccountTokenBalanceDao = *internal.AccountTokenBalanceDao

// accountTokenBalanceDao is the data access object for the table account_token_balance.
// You can define custom methods on it to extend its functionality as needed.
type accountTokenBalanceDao struct {
	internalAccountTokenBalanceDao
}

var (
	// AccountTokenBalance is a globally accessible object for table account_token_balance operations.
	AccountTokenBalance = accountTokenBalanceDao{
		internal.NewAccountTokenBalanceDao(),
	}
)

// Add your custom methods and functionality below.
