// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalAccountTokenBalanceLogDao is an internal type for wrapping the internal DAO implementation.
type internalAccountTokenBalanceLogDao = *internal.AccountTokenBalanceLogDao

// accountTokenBalanceLogDao is the data access object for the table account_token_balance_log.
// You can define custom methods on it to extend its functionality as needed.
type accountTokenBalanceLogDao struct {
	internalAccountTokenBalanceLogDao
}

var (
	// AccountTokenBalanceLog is a globally accessible object for table account_token_balance_log operations.
	AccountTokenBalanceLog = accountTokenBalanceLogDao{
		internal.NewAccountTokenBalanceLogDao(),
	}
)

// Add your custom methods and functionality below.
