// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalAnnouncementDao is an internal type for wrapping the internal DAO implementation.
type internalAnnouncementDao = *internal.AnnouncementDao

// announcementDao is the data access object for the table announcement.
// You can define custom methods on it to extend its functionality as needed.
type announcementDao struct {
	internalAnnouncementDao
}

var (
	// Announcement is a globally accessible object for table announcement operations.
	Announcement = announcementDao{
		internal.NewAnnouncementDao(),
	}
)

// Add your custom methods and functionality below.
