// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalHdContractEventDao is an internal type for wrapping the internal DAO implementation.
type internalHdContractEventDao = *internal.HdContractEventDao

// hdContractEventDao is the data access object for the table hd_contract_event.
// You can define custom methods on it to extend its functionality as needed.
type hdContractEventDao struct {
	internalHdContractEventDao
}

var (
	// HdContractEvent is a globally accessible object for table hd_contract_event operations.

	HdContractEvent = hdContractEventDao{
		internal.NewHdContractEventDao(),
	}
)

// Add your custom methods and functionality below.
