// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalNftTransferDao is an internal type for wrapping the internal DAO implementation.
type internalNftTransferDao = *internal.NftTransferDao

// nftTransferDao is the data access object for the table nft_transfer.
// You can define custom methods on it to extend its functionality as needed.
type nftTransferDao struct {
	internalNftTransferDao
}

var (
	// NftTransfer is a globally accessible object for table nft_transfer operations.
	NftTransfer = nftTransferDao{
		internal.NewNftTransferDao(),
	}
)

// Add your custom methods and functionality below.
