// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalNftStakingDao is an internal type for wrapping the internal DAO implementation.
type internalNftStakingDao = *internal.NftStakingDao

// nftStakingDao is the data access object for the table nft_staking.
// You can define custom methods on it to extend its functionality as needed.
type nftStakingDao struct {
	internalNftStakingDao
}

var (
	// NftStaking is a globally accessible object for table nft_staking operations.
	NftStaking = nftStakingDao{
		internal.NewNftStakingDao(),
	}
)

// Add your custom methods and functionality below.
