// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalNftBoxDao is an internal type for wrapping the internal DAO implementation.
type internalNftBoxDao = *internal.NftBoxDao

// nftBoxDao is the data access object for the table nft_box.
// You can define custom methods on it to extend its functionality as needed.
type nftBoxDao struct {
	internalNftBoxDao
}

var (
	// NftBox is a globally accessible object for table nft_box operations.
	NftBox = nftBoxDao{
		internal.NewNftBoxDao(),
	}
)

// Add your custom methods and functionality below.
