// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalNftHoldDao is an internal type for wrapping the internal DAO implementation.
type internalNftHoldDao = *internal.NftHoldDao

// nftHoldDao is the data access object for the table nft_hold.
// You can define custom methods on it to extend its functionality as needed.
type nftHoldDao struct {
	internalNftHoldDao
}

var (
	// NftHold is a globally accessible object for table nft_hold operations.
	NftHold = nftHoldDao{
		internal.NewNftHoldDao(),
	}
)

// Add your custom methods and functionality below.
