// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalNftStakingClaimDao is an internal type for wrapping the internal DAO implementation.
type internalNftStakingClaimDao = *internal.NftStakingClaimDao

// nftStakingClaimDao is the data access object for the table nft_staking_claim.
// You can define custom methods on it to extend its functionality as needed.
type nftStakingClaimDao struct {
	internalNftStakingClaimDao
}

var (
	// NftStakingClaim is a globally accessible object for table nft_staking_claim operations.
	NftStakingClaim = nftStakingClaimDao{
		internal.NewNftStakingClaimDao(),
	}
)

// Add your custom methods and functionality below.
