// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalNftBuyDao is an internal type for wrapping the internal DAO implementation.
type internalNftBuyDao = *internal.NftBuyDao

// nftBuyDao is the data access object for the table nft_buy.
// You can define custom methods on it to extend its functionality as needed.
type nftBuyDao struct {
	internalNftBuyDao
}

var (
	// NftBuy is a globally accessible object for table nft_buy operations.
	NftBuy = nftBuyDao{
		internal.NewNftBuyDao(),
	}
)

// Add your custom methods and functionality below.
