// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalRewardPoolJoinDao is an internal type for wrapping the internal DAO implementation.
type internalRewardPoolJoinDao = *internal.RewardPoolJoinDao

// rewardPoolJoinDao is the data access object for the table reward_pool_join.
// You can define custom methods on it to extend its functionality as needed.
type rewardPoolJoinDao struct {
	internalRewardPoolJoinDao
}

var (
	// RewardPoolJoin is a globally accessible object for table reward_pool_join operations.
	RewardPoolJoin = rewardPoolJoinDao{
		internal.NewRewardPoolJoinDao(),
	}
)

// Add your custom methods and functionality below.
