// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalRewardPoolSettlementDao is an internal type for wrapping the internal DAO implementation.
type internalRewardPoolSettlementDao = *internal.RewardPoolSettlementDao

// rewardPoolSettlementDao is the data access object for the table reward_pool_settlement.
// You can define custom methods on it to extend its functionality as needed.
type rewardPoolSettlementDao struct {
	internalRewardPoolSettlementDao
}

var (
	// RewardPoolSettlement is a globally accessible object for table reward_pool_settlement operations.
	RewardPoolSettlement = rewardPoolSettlementDao{
		internal.NewRewardPoolSettlementDao(),
	}
)

// Add your custom methods and functionality below.
