// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"nez-server/internal/dao/internal"
)

// internalRewardPoolClaimDao is an internal type for wrapping the internal DAO implementation.
type internalRewardPoolClaimDao = *internal.RewardPoolClaimDao

// rewardPoolClaimDao is the data access object for the table reward_pool_claim.
// You can define custom methods on it to extend its functionality as needed.
type rewardPoolClaimDao struct {
	internalRewardPoolClaimDao
}

var (
	// RewardPoolClaim is a globally accessible object for table reward_pool_claim operations.
	RewardPoolClaim = rewardPoolClaimDao{
		internal.NewRewardPoolClaimDao(),
	}
)

// Add your custom methods and functionality below.
